- name: "Git clone guiguts"
  ansible.builtin.git:
    repo: "https://github.com/DistributedProofreaders/guiguts-py.git"
    dest: "/home/ubuntu/guiguts-py"
    clone: true
    update: true
  tags:
    - "guiguts"

- name: "Git remote windymilla"
  ansible.builtin.shell:
    cmd: "git remote add windymilla https://github.com/windymilla/guiguts-py.git"
    chdir: "/home/ubuntu/guiguts-py"
    creates: "/home/ubuntu/guiguts-py/.git/refs/remotes/windymilla"
  tags:
    - "guiguts"

- name: "Git remote tangledhelix"
  ansible.builtin.shell:
    cmd: "git remote add tangledhelix https://github.com/tangledhelix/guiguts-py.git"
    chdir: "/home/ubuntu/guiguts-py"
    creates: "/home/ubuntu/guiguts-py/.git/refs/remotes/tangledhelix"
  tags:
    - "guiguts"
