- name: "Git clone guiguts-py"
  ansible.builtin.git:
    repo: "https://github.com/DistributedProofreaders/guiguts-py.git"
    dest: "/home/ubuntu/guiguts-py"
    clone: true
    update: true
  tags:
    - "guiguts"

- name: "guiguts-py remote windymilla"
  ansible.builtin.shell:
    cmd: "git remote add windymilla https://github.com/windymilla/guiguts-py.git"
    chdir: "/home/ubuntu/guiguts-py"
    creates: "/home/ubuntu/guiguts-py/.git/refs/remotes/windymilla"
  tags:
    - "guiguts"

- name: "guiguts-py remote tangledhelix"
  ansible.builtin.shell:
    cmd: "git remote add tangledhelix https://github.com/tangledhelix/guiguts-py.git"
    chdir: "/home/ubuntu/guiguts-py"
    creates: "/home/ubuntu/guiguts-py/.git/refs/remotes/tangledhelix"
  tags:
    - "guiguts"

- name: "Git clone guiguts"
  ansible.builtin.git:
    repo: "https://github.com/DistributedProofreaders/guiguts.git"
    dest: "/home/ubuntu/guiguts"
    clone: true
    update: true
  tags:
    - "guiguts"

- name: "Perl local::lib for GG1"
  ansible.builtin.shell:
    cmd: "cpanm local::lib"
    chdir: "/home/ubuntu"
    creates: "/home/ubuntu/perl5"
  tags:
    - "guiguts"

- name: "installer script for CPAN modules"
  ansible.builtin.copy:
    dest: "/home/ubuntu/gg1-cpan-installer"
    content: "#!/bin/sh\neval $(perl -I$HOME/perl5/lib -Mlocal::lib)\nperl install_cpan_modules.pl"
    mode: "0755"
  tags:
    - "guiguts"

- name: "Install CPAN modules for GG1"
  ansible.builtin.shell:
    cmd: "/home/ubuntu/gg1-cpan-installer"
    chdir: "/home/ubuntu/guiguts"
  tags:
    - "guiguts"
