- name: "Install desktop packages"
  ansible.builtin.apt:
    name: "ubuntu-desktop"
    state: "latest"
  become: true
  tags:
    - "desktop"

- name: "Disable screen lock"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.screensaver lock-enabled false"
  tags:
    - "desktop"

- name: "Disable screen blank"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.session idle-delay 0"
  tags:
    - "desktop"

- name: "Enable natural scroll"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.peripherals.mouse natural-scroll true"
  tags:
    - "desktop"

- name: "Enable automatic login"
  ansible.builtin.shell:
    cmd: "sed -i -e 's/^#.*\\(AutomaticLoginEnable = true\\)/\\1/' /etc/gdm3/custom.conf"
  become: true
  tags:
    - "desktop"

- name: "Set automatic login user"
  ansible.builtin.shell:
    cmd: "sed -i -e 's/^#.*\\(AutomaticLogin =\\) user1/\\1 ubuntu/' /etc/gdm3/custom.conf"
  become: true
  tags:
    - "desktop"

- name: "Set login shell"
  ansible.builtin.shell:
    cmd: "chsh -s /bin/zsh ubuntu"
  become: true
  tags:
    - "desktop"

- name: "Git clone dotfiles"
  ansible.builtin.git:
    repo: "https://github.com/tangledhelix/dotfiles.git"
    dest: "/home/ubuntu/dotfiles"
    clone: true
    update: true
  tags:
    - "desktop"

- name: "dotfiles inventory"
  ansible.builtin.file:
    path: "/home/ubuntu/dotfiles/inventory"
    state: "directory"
  tags:
    - "desktop"

- name: "dotfiles inventory/hosts"
  ansible.builtin.copy:
    dest: "/home/ubuntu/dotfiles/inventory/hosts"
    content: "[all]\nlocalhost ansible_connection=local\n[local]\nlocalhost ansible_connection=local"

- name: "Install dotfiles"
  ansible.builtin.shell:
    cmd: "ansible-playbook -l localhost main.yml"
    chdir: "/home/ubuntu/dotfiles"
  tags:
    - "desktop"
