- name: "Install desktop packages"
  ansible.builtin.apt:
    name: "ubuntu-desktop"
    state: "latest"
  become: true
  tags:
    - "desktop"

- name: "Disable screen lock"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.screensaver lock-enabled false"
  tags:
    - "desktop"

- name: "Disable screen blank"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.session idle-delay 0"
  tags:
    - "desktop"

- name: "Enable natural scroll"
  ansible.builtin.shell:
    cmd: "gsettings set org.gnome.desktop.peripherals.mouse natural-scroll true"
  tags:
    - "desktop"

- name: "Enable automatic login"
  ansible.builtin.shell:
    cmd: "sed -i -e 's/^#.*\\(AutomaticLoginEnable = true\\)/\\1/' /etc/gdm3/custom.conf"
  become: true
  tags:
    - "desktop"

- name: "Set automatic login user"
  ansible.builtin.shell:
    cmd: "sed -i -e 's/^#.*\\(AutomaticLogin =\\) user1/\\1 ubuntu/' /etc/gdm3/custom.conf"
  become: true
  tags:
    - "desktop"
