- name: "Install packages"
  ansible.builtin.apt:
    name: "{{item}}"
    state: "latest"
  with_items:
    - "python3-pip"
    - "python3-poetry"
    - "python3-tk"
    - "pipenv"
    - "idle-python3.12"
    - "neovim"
    - "ripgrep"
    - "nodejs"
    - "tree-sitter-cli"
  tags:
    - "apt"
