- name: "Install packages for GG2"
  ansible.builtin.apt:
    name: "{{item}}"
    state: "latest"
  with_items:
    - "python3-pip"
    - "python3-poetry"
    - "python3-tk"
    - "pipenv"
    - "idle-python3.12"
  become: true
  tags:
    - "apt"

- name: "Install packages for GG1"
  ansible.builtin.apt:
    name: "{{item}}"
    state: "latest"
  with_items:
    - "perl-base"
    - "cpanminus"
    - "libx11-dev"
    - "zlib1g-dev"
    - "gcc"
