- name: "Sudo config"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/ubuntu-user"
    owner: "root"
    group: "root"
    mode: "0440"
    content: "ubuntu ALL=NOPASSWD: ALL"
  become: true
  tags:
    - "sudo"
